//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanças.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clientesBDEntities3 : DbContext
    {
        public clientesBDEntities3()
            : base("name=clientesBDEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<details> details1 { get; set; }
        public virtual DbSet<v_clients> v_clients { get; set; }
        public virtual DbSet<expense> expenses { get; set; }
        public virtual DbSet<type_of_expenses> type_of_expenses { get; set; }
        public virtual DbSet<v_expense> v_expense { get; set; }
        public virtual DbSet<type_Of_Payment> type_Of_Payment { get; set; }
    }
}
