//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanças.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int idfaturadet { get; set; }
        public Nullable<int> idfatura { get; set; }
        public Nullable<System.DateTime> date_payment { get; set; }
        public Nullable<decimal> value_Of_Paymente { get; set; }
    
        public virtual expense expense { get; set; }
    }
}
