//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanças.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public expense()
        {
            this.details = new HashSet<detail>();
        }
    
        public int idfatura { get; set; }
        public Nullable<int> idcli { get; set; }
        public Nullable<System.DateTime> dataFirstPayment { get; set; }
        public Nullable<int> type_Of_Expense { get; set; }
        public Nullable<int> type_Of_Payment { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail> details { get; set; }
    }
}
